# Generated by Django 3.1.3 on 2020-12-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
        ('cauldron', '0003_iaddowner_gl_gh'),
    ]

    operations = [
        migrations.CreateModel(
            name='IExportGitCSVArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Export Git CSV Intentions Archived',
                'db_table': 'poolsched_export_git_csv_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IExportGitCSV',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Export Git CSV Intentions',
                'db_table': 'poolsched_export_git_csv',
            },
            bases=('poolsched.intention',),
        ),
    ]
