# Generated by Django 3.1.3 on 2020-12-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0003_iaddowner_gl_gh'),
        ('poolsched_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexportgitcsv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iexport_git_csv', to='cauldron.project'),
        ),
        migrations.CreateModel(
            name='GitCSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_csv_file', to='cauldron.project')),
            ],
        ),
    ]
