# Generated by Django 3.1.3 on 2021-04-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0001_initial'),
        ('cauldron', '0016_auto_20210427_1020'),
        ('poolsched_export', '0002_auto_20201215_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='IExportCSV',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('backend', models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup'), ('SE', 'StackExchange'), ('UK', 'Unknown')], max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iexport_csv', to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Export CSV Intentions',
                'db_table': 'poolsched_export_csv',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IExportCSVArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('backend', models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup'), ('SE', 'StackExchange'), ('UK', 'Unknown')], max_length=2)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Export CSV Intentions Archived',
                'db_table': 'poolsched_export_csv_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='ProjectExportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=150)),
                ('size', models.IntegerField()),
                ('backend', models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup'), ('SE', 'StackExchange'), ('UK', 'Unknown')], max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_exported', to='cauldron.project')),
            ],
        ),
        migrations.DeleteModel(
            name='GitCSVFile',
        ),
        migrations.DeleteModel(
            name='IExportGitCSV',
        ),
        migrations.DeleteModel(
            name='IExportGitCSVArchived',
        ),
    ]
