# Generated by Django 3.1.3 on 2021-06-17 11:23

import cauldron_apps.poolsched_export.models.ireport_kbn
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0019_auto_20210609_0809'),
        ('poolsched', '0001_initial'),
        ('poolsched_export', '0003_auto_20210427_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKibanaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(default='all', max_length=200)),
                ('dashboard_name', models.CharField(default='All dashboards', max_length=200)),
                ('format', models.CharField(default='pdf', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField(default=cauldron_apps.poolsched_export.models.ireport_kbn.one_year_before)),
                ('to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default=None, max_length=150, null=True)),
                ('progress', models.CharField(default='pending', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kbn_report', to='cauldron.project')),
            ],
        ),
        migrations.CreateModel(
            name='IReportKbnArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('kbn_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikbn_report_archived', to='poolsched_export.projectkibanareport')),
            ],
            options={
                'verbose_name_plural': 'Kibana Report Archived',
                'db_table': 'poolsched_kbn_report_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IReportKbn',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('kbn_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikbn_report', to='poolsched_export.projectkibanareport')),
            ],
            options={
                'verbose_name_plural': 'Kibana report intention',
                'db_table': 'poolsched_kbn_report',
            },
            bases=('poolsched.intention',),
        ),
    ]
