# Generated by Django 3.1.3 on 2021-10-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0001_initial'),
        ('poolsched_export', '0004_ireportkbn_ireportkbnarchived_projectkibanareport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICommitsByMonth',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('progress', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Export Commits Intentions',
                'db_table': 'poolsched_export_commits',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='ICommitsByMonthArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
            ],
            options={
                'verbose_name_plural': 'Export Commits Intentions Archived',
                'db_table': 'poolsched_export_commits_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='ReportsCommitsByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
