# Generated by Django 3.1.3 on 2021-11-05 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poolsched', '0002_scheduledintention'),
        ('poolsched_export', '0005_commitsbymonth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ICommitsByMonth',
            new_name='ICommitsByWeek',
        ),
        migrations.RenameModel(
            old_name='ICommitsByMonthArchived',
            new_name='ICommitsByWeekArchived',
        ),
        migrations.RenameModel(
            old_name='ReportsCommitsByMonth',
            new_name='ReportsCommitsByWeek',
        ),
    ]
