# Generated by Django 3.1.3 on 2020-11-23 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GLInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('endpoint', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'poolsched_glinstance',
            },
        ),
        migrations.CreateModel(
            name='GLRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=40)),
                ('repo', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poolsched_gitlab.glinstance')),
            ],
            options={
                'verbose_name_plural': 'Repositories GitLab',
                'db_table': 'poolsched_glrepo',
                'unique_together': {('owner', 'repo', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='IGLRawArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_gitlab.glrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitLabRaw',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGLRaw',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_gitlab.glrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GLRaw',
                'db_table': 'poolsched_gliraw',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGLEnrichArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_gitlab.glrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitLabEnrich',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGLEnrich',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_gitlab.glrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GLEnrich',
                'db_table': 'poolsched_glienriched',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='GLToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobs', models.ManyToManyField(related_name='gltokens', related_query_name='gltoken', to='poolsched.Job')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gltokens', related_query_name='gltoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tokens GitLab',
                'db_table': 'poolsched_gltoken',
            },
        ),
    ]
