# Generated by Django 3.1.3 on 2020-12-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0001_initial'),
        ('poolsched_gitlab', '0002_gitlab_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGLIssueAutoRefresh',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GL Issue Autorefresh',
                'db_table': 'poolsched_gl_issue_autorefresh',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGLIssueAutoRefreshArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GL Issue Autorefresh Archived',
                'db_table': 'poolsched_gl_issue_autorefresh_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGLMergeAutoRefresh',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GL Merge Autorefresh',
                'db_table': 'poolsched_gl_merge_autorefresh',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGLMergeAutoRefreshArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GL Merge Autorefresh Archived',
                'db_table': 'poolsched_gl_merge_autorefresh_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
    ]
