# Generated by Django 3.1.3 on 2021-01-14 15:30

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_gitlab', '0004_auto_20201221_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='glinstance',
            name='client_id',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='glinstance',
            name='client_secret',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='glinstance',
            name='slug',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
