# Generated by Django 3.2.15 on 2022-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_gitlab', '0006_auto_20210114_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='gltoken',
            name='expiration_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='gltoken',
            name='expiring_token',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gltoken',
            name='refresh_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
