# Generated by Django 3.1.3 on 2021-02-02 10:40

from django.db import migrations
from cauldron_apps.poolsched_gitlab.models import GLInstance


def gitlab_data(apps, schema_editor):
    GLInstance.objects.update_or_create(
        name='KDE',
        endpoint="https://invent.kde.org",
        slug='kde')


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_gitlab', '0006_auto_20210114_1530'),
    ]

    operations = [
        migrations.RunPython(gitlab_data),
    ]
