# Generated by Django 3.1.3 on 2021-01-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cauldron', '0003_iaddowner_gl_gh'),
        ('poolsched_gitlab', '0003_gl_autorefresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Actions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddGitHubOwnerAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Add GitHub owner actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='RemoveMeetupRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.meetuprepository')),
            ],
            options={
                'verbose_name_plural': 'Remove Meetup repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='RemoveGitRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.gitrepository')),
            ],
            options={
                'verbose_name_plural': 'Remove Git repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='RemoveGitLabRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.gitlabrepository')),
            ],
            options={
                'verbose_name_plural': 'Remove GitLab repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='RemoveGitHubRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.githubrepository')),
            ],
            options={
                'verbose_name_plural': 'Remove GitHub repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddMeetupRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.meetuprepository')),
            ],
            options={
                'verbose_name_plural': 'Add Meetup repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddGitRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.gitrepository')),
            ],
            options={
                'verbose_name_plural': 'Add Git repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddGitLabRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.gitlabrepository')),
            ],
            options={
                'verbose_name_plural': 'Add GitLab repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddGitLabOwnerAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolsched_gitlab.glinstance')),
            ],
            options={
                'verbose_name_plural': 'Add GitLab owner actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddGitHubRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.githubrepository')),
            ],
            options={
                'verbose_name_plural': 'Add GitHub repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
    ]
