# Generated by Django 3.1.3 on 2021-03-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0012_auto_20210311_1658'),
        ('cauldron_actions', '0002_irefreshactions_irefreshactionsarchived'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveStackExchangeRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.stackexchangerepository')),
            ],
            options={
                'verbose_name_plural': 'Remove StackExchange repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
        migrations.CreateModel(
            name='AddStackExchangeRepoAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cauldron_actions.action')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.stackexchangerepository')),
            ],
            options={
                'verbose_name_plural': 'Add StackExchange repo actions',
            },
            bases=('cauldron_actions.action',),
        ),
    ]
