# Generated by Django 3.1.3 on 2020-12-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMergeIdentities',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Merge Identities',
                'db_table': 'poolsched_merge_identities',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IMergeIdentitiesArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Merge Identities Archived',
                'db_table': 'poolsched_merge_identities_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
    ]
