# Generated by Django 3.1.3 on 2020-12-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_gitlab', '0003_gl_autorefresh'),
        ('poolsched', '0001_initial'),
        ('cauldron', '0002_auto_20201123_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAddGLOwnerArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('intention_id', models.IntegerField()),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('analyze', models.BooleanField(default=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.project')),
            ],
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IAddGLOwner',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=False)),
                ('analyze', models.BooleanField(default=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolsched_gitlab.glinstance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IAddGHOwnerArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('intention_id', models.IntegerField()),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('analyze', models.BooleanField(default=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.project')),
            ],
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IAddGHOwner',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('owner', models.CharField(max_length=128)),
                ('commits', models.BooleanField(default=True)),
                ('issues', models.BooleanField(default=True)),
                ('forks', models.BooleanField(default=False)),
                ('analyze', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            bases=('poolsched.intention',),
        ),
    ]
