# Generated by Django 3.1.3 on 2020-12-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_github', '0004_auto_20201221_1619'),
        ('poolsched_gitlab', '0004_auto_20201221_1619'),
        ('cauldron', '0003_iaddowner_gl_gh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SHTask',
        ),
        migrations.AddField(
            model_name='iaddghowner',
            name='instance',
            field=models.ForeignKey(default='GitHub', on_delete=django.db.models.deletion.CASCADE, to='poolsched_github.ghinstance', to_field='name'),
        ),
        migrations.AddField(
            model_name='iaddghownerarchived',
            name='instance',
            field=models.ForeignKey(default='GitHub', on_delete=django.db.models.deletion.CASCADE, to='poolsched_github.ghinstance', to_field='name'),
        ),
        migrations.AddField(
            model_name='iaddglownerarchived',
            name='instance',
            field=models.ForeignKey(default='GitLab', on_delete=django.db.models.deletion.CASCADE, to='poolsched_gitlab.glinstance', to_field='name'),
        ),
        migrations.AlterField(
            model_name='iaddglowner',
            name='instance',
            field=models.ForeignKey(default='GitLab', on_delete=django.db.models.deletion.CASCADE, to='poolsched_gitlab.glinstance', to_field='name'),
        ),
    ]
