# Generated by Django 3.1.3 on 2020-12-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poolsched_gitlab', '0004_auto_20201221_1619'),
        ('cauldron', '0004_instance_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepository',
            name='instance',
            field=models.ForeignKey(blank=True, default='GitLab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poolsched_gitlab.glinstance', to_field='name'),
        ),
        migrations.CreateModel(
            name='GnomeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
