# Generated by Django 3.1.4 on 2021-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0005_auto_20201222_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='backend',
            field=models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('MU', 'Meetup')], default='UK', max_length=2),
        ),
    ]

