# Generated by Django 3.1.3 on 2021-01-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0008_migrate_oauthuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gnomeuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meetupuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='GithubUser',
        ),
        migrations.DeleteModel(
            name='GitlabUser',
        ),
        migrations.DeleteModel(
            name='GnomeUser',
        ),
        migrations.DeleteModel(
            name='MeetupUser',
        ),
    ]
