# Generated by Django 3.1.6 on 2021-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0009_remove_old_oauthusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthuser',
            name='photo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='backend',
            field=models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup')], default='UK', max_length=2),
        ),
    ]
