# Generated by Django 3.1.3 on 2021-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0010_auto_20210202_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedBackendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('username', 'backend')},
            },
        ),
    ]
