# Generated by Django 3.1.3 on 2021-03-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0011_authorizedbackenduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackExchangeRepository',
            fields=[
                ('site', models.CharField(max_length=100)),
                ('tagged', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stackexchange', serialize=False, to='cauldron.repository')),
            ],
            options={
                'verbose_name_plural': 'StackExchange tags',
            },
            bases=('cauldron.repository',),
        ),
        migrations.AlterField(
            model_name='repository',
            name='backend',
            field=models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup'), ('SE', 'StackExchange')], default='UK', max_length=2),
        ),
    ]
