# Generated by Django 3.1.3 on 2021-03-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0012_auto_20210311_1658'),
        ('poolsched_stackexchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackexchangerepository',
            name='repo_sched',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poolsched_stackexchange.stackexchangequestiontag'),
        ),
        migrations.AlterUniqueTogether(
            name='stackexchangerepository',
            unique_together={('site', 'tagged')},
        ),
    ]
