# Generated by Django 3.1.8 on 2021-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0014_bannermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermessage',
            name='text_color',
            field=models.TextField(default='text-dark'),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='border_color',
            field=models.TextField(default='border-left-primary'),
        ),
        migrations.AddField(
            model_name='bannermessage',
            name='color',
            field=models.TextField(default='alert-info'),
        ),
    ]
