# Generated by Django 3.1.3 on 2021-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0015_bannermessage_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='backend',
            field=models.CharField(choices=[('GI', 'Git'), ('GH', 'GitHub'), ('GL', 'GitLab'), ('GN', 'Gnome'), ('KD', 'KDE'), ('MU', 'Meetup'), ('SE', 'StackExchange'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
    ]
