# Generated by Django 3.1.3 on 2021-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0017_project_fork_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_refresh',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
