# Generated by Django 3.1.3 on 2021-06-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0018_repository_last_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('commits', models.IntegerField(default=0)),
                ('issues', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='metrics',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.repositorymetrics'),
        ),
    ]
