# Generated by Django 3.1.3 on 2021-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0020_project_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorymetrics',
            name='commits_authors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorymetrics',
            name='issues_submitters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorymetrics',
            name='reviews_submitters',
            field=models.IntegerField(default=0),
        ),
    ]
