# Generated by Django 3.1.3 on 2021-11-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0002_scheduledintention'),
        ('cauldron', '0021_auto_20210701_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRefreshProjectArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('intention_id', models.IntegerField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauldron.project')),
            ],
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IRefreshProject',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            bases=('poolsched.intention',),
        ),
    ]
