# Generated by Django 3.1.3 on 2021-11-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron', '0022_irefreshproject_irefreshprojectarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autorefresh',
            field=models.BooleanField(default=False),
        ),
    ]
