# Generated by Django 3.1.3 on 2020-11-23 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Repositories Git',
                'db_table': 'poolsched_gitrepo',
            },
        ),
        migrations.CreateModel(
            name='IGitRawArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_git.gitrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitRaw',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGitRaw',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_git.gitrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GitRaw',
                'db_table': 'poolsched_gitiraw',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGitEnrichArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_git.gitrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitEnrich',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGitEnrich',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_git.gitrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GitEnrich',
                'db_table': 'poolsched_gitienriched',
            },
            bases=('poolsched.intention',),
        ),
    ]
