# Generated by Django 3.1.3 on 2020-11-23 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GHInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('endpoint', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'poolsched_ghinstance',
            },
        ),
        migrations.CreateModel(
            name='GHRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=40)),
                ('repo', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poolsched_github.ghinstance')),
            ],
            options={
                'verbose_name_plural': 'Repositories GitHub',
                'db_table': 'poolsched_ghrepo',
                'unique_together': {('owner', 'repo', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='IGHRawArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_github.ghrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitHubRaw',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGHRaw',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_github.ghrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GHRaw',
                'db_table': 'poolsched_ghiraw',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGHEnrichArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_github.ghrepo')),
            ],
            options={
                'verbose_name_plural': 'Archived GitHubEnrich',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGHEnrich',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_github.ghrepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions GHEnrich',
                'db_table': 'poolsched_ghienriched',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='GHToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobs', models.ManyToManyField(related_name='ghtokens', related_query_name='ghtoken', to='poolsched.Job')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghtokens', related_query_name='ghtoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tokens GitHub',
                'db_table': 'poolsched_ghtoken',
            },
        ),
    ]
