# Generated by Django 3.1.3 on 2020-12-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0001_initial'),
        ('poolsched_github', '0002_github_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGH2IssueAutoRefresh',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH2 Issue Autorefresh',
                'db_table': 'poolsched_gh2_issue_autorefresh',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGH2IssueAutoRefreshArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH2 Issue Autorefresh Archived',
                'db_table': 'poolsched_gh2_issue_autorefresh_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGHIssueAutoRefresh',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH Issue Autorefresh',
                'db_table': 'poolsched_gh_issue_autorefresh',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGHIssueAutoRefreshArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH Issue Autorefresh Archived',
                'db_table': 'poolsched_gh_issue_autorefresh_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IGHRepoAutoRefresh',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH Repo Autorefresh',
                'db_table': 'poolsched_gh_repo_autorefresh',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IGHRepoAutoRefreshArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('last_autorefresh', models.DateTimeField(null=True)),
                ('scheduled', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'GH Repo Autorefresh Archived',
                'db_table': 'poolsched_gh_repo_autorefresh_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
    ]
