# Generated by Django 3.1.7 on 2021-04-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
        ('cauldron', '0014_bannermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITwitterNotifyArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Twitter Notify Archived',
                'db_table': 'poolsched_twitter_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='ITwitterNotify',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cauldron.project')),
            ],
            options={
                'verbose_name_plural': 'Twitter Notify Intentions',
                'db_table': 'poolsched_twitter_intention',
            },
            bases=('poolsched.intention',),
        ),
    ]
