# Generated by Django 3.1.7 on 2021-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched_twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itwitternotify',
            name='report_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
