# Generated by Django 3.1.3 on 2021-10-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poolsched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPDXUserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('result', models.JSONField(default=None, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spdx_user_files', related_query_name='spdx_user_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IParseSPDXArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_sbom.spdxuserfile')),
            ],
            options={
                'verbose_name_plural': 'SPDX parsers',
                'db_table': 'poolsched_parse_SPDX_archived',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IParseSPDX',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('spdx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolsched_sbom.spdxuserfile')),
            ],
            options={
                'verbose_name_plural': 'Intentions ParseSPDX',
                'db_table': 'poolsched_sbom_iparse',
            },
            bases=('poolsched.intention',),
        ),
    ]
