# Generated by Django 3.1.3 on 2020-11-23 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poolsched', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Repositories Meetup',
                'db_table': 'poolsched_meetuprepo',
            },
        ),
        migrations.CreateModel(
            name='MeetupToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('refresh_token', models.CharField(max_length=50)),
                ('reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobs', models.ManyToManyField(related_name='meetuptokens', related_query_name='meetuptoken', to='poolsched.Job')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetuptokens', related_query_name='meetuptoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tokens Meetup',
                'db_table': 'poolsched_meetuptoken',
            },
        ),
        migrations.CreateModel(
            name='IMeetupRawArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_meetup.meetuprepo')),
            ],
            options={
                'verbose_name_plural': 'Archived MeetupRaw',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IMeetupRaw',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_meetup.meetuprepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions MeetRaw',
                'db_table': 'poolsched_meetupiraw',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IMeetupEnrichArchived',
            fields=[
                ('archivedintention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.archivedintention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_meetup.meetuprepo')),
            ],
            options={
                'verbose_name_plural': 'Archived MeetupEnrich',
            },
            bases=('poolsched.archivedintention',),
        ),
        migrations.CreateModel(
            name='IMeetupEnrich',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched_meetup.meetuprepo')),
            ],
            options={
                'verbose_name_plural': 'Intentions MeetEnrich',
                'db_table': 'poolsched_meetupienriched',
            },
            bases=('poolsched.intention',),
        ),
    ]
